import { NextResponse } from 'next/server'
import { createAdminClient } from '@/lib/supabase/admin'
import type { Database } from '@/types/database'

type ProviderInsert = Database['public']['Tables']['providers']['Insert']

// Seed data for 25 providers across 5 service categories and 5 cities
const providers: ProviderInsert[] = [
  // AC Technicians (6)
  {
    id: 'P001',
    name: 'Usman AC Services',
    phone: '0300-1234567',
    skill: 'AC Repair',
    specializations: ['Split AC', 'Window AC', 'Gas Refill', 'Installation'],
    job_complexity_handled: ['basic', 'intermediate', 'complex'],
    certifications: ['HVAC Certified', 'Samsung Authorized'],
    city: 'Islamabad',
    areas: ['G-13', 'G-11', 'F-10', 'F-8', 'I-8'],
    lat: 33.6844,
    lng: 73.0479,
    rating: 4.7,
    total_reviews: 312,
    recent_review_date: '2026-05-16',
    recent_review_sentiment: 'positive',
    on_time_score: 91,
    cancellation_rate: 3,
    reliability_score: 88,
    risk_score: 'low',
    dispute_count: 1,
    visit_fee: 500,
    hourly_rate_pkr: 1500,
    rate_per_km: 20,
    loyalty_discount: 5,
    available: true,
    booked_slots: [],
    max_daily_capacity: 4,
    current_day_bookings: 2,
    years_experience: 8,
    languages_spoken: ['Urdu', 'Punjabi'],
    tier: 'premium',
  },
  {
    id: 'P002',
    name: 'Ali AC & Refrigeration',
    phone: '0301-2345678',
    skill: 'AC Repair',
    specializations: ['Split AC', 'Central AC', 'Compressor'],
    job_complexity_handled: ['basic', 'intermediate', 'complex'],
    certifications: ['LG Authorized'],
    city: 'Islamabad',
    areas: ['F-7', 'F-6', 'G-6', 'G-5'],
    lat: 33.7294,
    lng: 73.0931,
    rating: 4.5,
    total_reviews: 245,
    recent_review_date: '2026-05-10',
    recent_review_sentiment: 'positive',
    on_time_score: 85,
    cancellation_rate: 5,
    reliability_score: 82,
    risk_score: 'low',
    dispute_count: 2,
    visit_fee: 400,
    hourly_rate_pkr: 1200,
    rate_per_km: 20,
    loyalty_discount: 5,
    available: true,
    booked_slots: [],
    max_daily_capacity: 5,
    current_day_bookings: 3,
    years_experience: 6,
    languages_spoken: ['Urdu'],
    tier: 'standard',
  },
  {
    id: 'P003',
    name: 'Bilal Cooling Solutions',
    phone: '0302-3456789',
    skill: 'AC Repair',
    specializations: ['Window AC', 'Gas Refill'],
    job_complexity_handled: ['basic', 'intermediate'],
    certifications: [],
    city: 'Karachi',
    areas: ['Defence', 'Clifton', 'Gulshan'],
    lat: 24.8607,
    lng: 67.0011,
    rating: 4.2,
    total_reviews: 178,
    recent_review_date: '2026-05-01',
    recent_review_sentiment: 'neutral',
    on_time_score: 67,
    cancellation_rate: 8,
    reliability_score: 70,
    risk_score: 'medium',
    dispute_count: 4,
    visit_fee: 350,
    hourly_rate_pkr: 1000,
    rate_per_km: 25,
    loyalty_discount: 0,
    available: true,
    booked_slots: [],
    max_daily_capacity: 3,
    current_day_bookings: 1,
    years_experience: 4,
    languages_spoken: ['Urdu', 'Sindhi'],
    tier: 'basic',
  },
  {
    id: 'P004',
    name: 'Hamza HVAC Tech',
    phone: '0303-4567890',
    skill: 'AC Repair',
    specializations: ['Split AC', 'Ducted AC', 'Installation'],
    job_complexity_handled: ['basic', 'intermediate', 'complex'],
    certifications: ['Daikin Certified'],
    city: 'Lahore',
    areas: ['Gulberg', 'DHA', 'Model Town'],
    lat: 31.5204,
    lng: 74.3587,
    rating: 4.8,
    total_reviews: 420,
    recent_review_date: '2026-05-18',
    recent_review_sentiment: 'positive',
    on_time_score: 95,
    cancellation_rate: 1,
    reliability_score: 94,
    risk_score: 'low',
    dispute_count: 0,
    visit_fee: 600,
    hourly_rate_pkr: 1800,
    rate_per_km: 20,
    loyalty_discount: 10,
    available: true,
    booked_slots: [],
    max_daily_capacity: 4,
    current_day_bookings: 2,
    years_experience: 12,
    languages_spoken: ['Urdu', 'Punjabi', 'English'],
    tier: 'premium',
  },
  {
    id: 'P005',
    name: 'Tariq AC Master',
    phone: '0304-5678901',
    skill: 'AC Repair',
    specializations: ['Split AC', 'Window AC'],
    job_complexity_handled: ['basic', 'intermediate'],
    certifications: [],
    city: 'Lahore',
    areas: ['Johar Town', 'Faisal Town'],
    lat: 31.4697,
    lng: 74.2728,
    rating: 4.0,
    total_reviews: 89,
    recent_review_date: '2026-04-20',
    recent_review_sentiment: 'neutral',
    on_time_score: 72,
    cancellation_rate: 10,
    reliability_score: 65,
    risk_score: 'medium',
    dispute_count: 3,
    visit_fee: 300,
    hourly_rate_pkr: 900,
    rate_per_km: 15,
    loyalty_discount: 0,
    available: true,
    booked_slots: [],
    max_daily_capacity: 3,
    current_day_bookings: 2,
    years_experience: 3,
    languages_spoken: ['Urdu'],
    tier: 'basic',
  },
  {
    id: 'P006',
    name: 'Kashif Climate Control',
    phone: '0305-6789012',
    skill: 'AC Repair',
    specializations: ['Central AC', 'VRF Systems'],
    job_complexity_handled: ['complex'],
    certifications: ['Carrier Authorized', 'HVAC Certified'],
    city: 'Peshawar',
    areas: ['University Town', 'Hayatabad'],
    lat: 34.0151,
    lng: 71.5249,
    rating: 4.6,
    total_reviews: 156,
    recent_review_date: '2026-05-12',
    recent_review_sentiment: 'positive',
    on_time_score: 88,
    cancellation_rate: 4,
    reliability_score: 85,
    risk_score: 'low',
    dispute_count: 1,
    visit_fee: 450,
    hourly_rate_pkr: 1400,
    rate_per_km: 20,
    loyalty_discount: 5,
    available: true,
    booked_slots: [],
    max_daily_capacity: 3,
    current_day_bookings: 1,
    years_experience: 9,
    languages_spoken: ['Urdu', 'Pashto'],
    tier: 'premium',
  },

  // Electricians (5)
  {
    id: 'P007',
    name: 'Ahmad Electric Works',
    phone: '0306-7890123',
    skill: 'Electrician',
    specializations: ['Wiring', 'Lighting', 'Panel Board'],
    job_complexity_handled: ['basic', 'intermediate', 'complex'],
    certifications: ['Licensed Electrician'],
    city: 'Islamabad',
    areas: ['G-13', 'G-11', 'I-8', 'I-10'],
    lat: 33.6500,
    lng: 73.0500,
    rating: 4.4,
    total_reviews: 267,
    recent_review_date: '2026-05-14',
    recent_review_sentiment: 'positive',
    on_time_score: 82,
    cancellation_rate: 6,
    reliability_score: 78,
    risk_score: 'low',
    dispute_count: 2,
    visit_fee: 400,
    hourly_rate_pkr: 1000,
    rate_per_km: 20,
    loyalty_discount: 5,
    available: true,
    booked_slots: [],
    max_daily_capacity: 5,
    current_day_bookings: 3,
    years_experience: 10,
    languages_spoken: ['Urdu'],
    tier: 'standard',
  },
  {
    id: 'P008',
    name: 'Raza Electrical Services',
    phone: '0307-8901234',
    skill: 'Electrician',
    specializations: ['House Wiring', 'Fault Finding'],
    job_complexity_handled: ['basic', 'intermediate'],
    certifications: [],
    city: 'Karachi',
    areas: ['North Nazimabad', 'Gulistan-e-Jauhar'],
    lat: 24.9200,
    lng: 67.0800,
    rating: 4.1,
    total_reviews: 134,
    recent_review_date: '2026-04-28',
    recent_review_sentiment: 'positive',
    on_time_score: 75,
    cancellation_rate: 7,
    reliability_score: 72,
    risk_score: 'medium',
    dispute_count: 3,
    visit_fee: 350,
    hourly_rate_pkr: 800,
    rate_per_km: 25,
    loyalty_discount: 0,
    available: true,
    booked_slots: [],
    max_daily_capacity: 4,
    current_day_bookings: 2,
    years_experience: 5,
    languages_spoken: ['Urdu', 'Sindhi'],
    tier: 'basic',
  },
  {
    id: 'P009',
    name: 'Faisal Power Solutions',
    phone: '0308-9012345',
    skill: 'Electrician',
    specializations: ['Industrial Wiring', 'Generator', 'UPS'],
    job_complexity_handled: ['intermediate', 'complex'],
    certifications: ['Licensed Electrician', 'Safety Certified'],
    city: 'Lahore',
    areas: ['Township', 'Iqbal Town'],
    lat: 31.4800,
    lng: 74.2900,
    rating: 4.6,
    total_reviews: 298,
    recent_review_date: '2026-05-15',
    recent_review_sentiment: 'positive',
    on_time_score: 90,
    cancellation_rate: 2,
    reliability_score: 88,
    risk_score: 'low',
    dispute_count: 1,
    visit_fee: 500,
    hourly_rate_pkr: 1300,
    rate_per_km: 20,
    loyalty_discount: 5,
    available: true,
    booked_slots: [],
    max_daily_capacity: 4,
    current_day_bookings: 1,
    years_experience: 11,
    languages_spoken: ['Urdu', 'Punjabi'],
    tier: 'premium',
  },
  {
    id: 'P010',
    name: 'Imran Electric',
    phone: '0309-0123456',
    skill: 'Electrician',
    specializations: ['Lighting', 'Fan Repair'],
    job_complexity_handled: ['basic'],
    certifications: [],
    city: 'Multan',
    areas: ['Bosan Road', 'Shah Rukn-e-Alam'],
    lat: 30.1575,
    lng: 71.5249,
    rating: 3.8,
    total_reviews: 56,
    recent_review_date: '2026-03-15',
    recent_review_sentiment: 'neutral',
    on_time_score: 60,
    cancellation_rate: 12,
    reliability_score: 55,
    risk_score: 'medium',
    dispute_count: 5,
    visit_fee: 250,
    hourly_rate_pkr: 600,
    rate_per_km: 15,
    loyalty_discount: 0,
    available: true,
    booked_slots: [],
    max_daily_capacity: 3,
    current_day_bookings: 1,
    years_experience: 2,
    languages_spoken: ['Urdu', 'Saraiki'],
    tier: 'basic',
  },
  {
    id: 'P011',
    name: 'Naveed Electrical',
    phone: '0310-1234567',
    skill: 'Electrician',
    specializations: ['Solar Installation', 'Inverter'],
    job_complexity_handled: ['intermediate', 'complex'],
    certifications: ['Solar Certified'],
    city: 'Peshawar',
    areas: ['Saddar', 'Kohati Bazar'],
    lat: 34.0100,
    lng: 71.5800,
    rating: 4.3,
    total_reviews: 112,
    recent_review_date: '2026-05-05',
    recent_review_sentiment: 'positive',
    on_time_score: 78,
    cancellation_rate: 5,
    reliability_score: 75,
    risk_score: 'low',
    dispute_count: 2,
    visit_fee: 400,
    hourly_rate_pkr: 1100,
    rate_per_km: 20,
    loyalty_discount: 5,
    available: true,
    booked_slots: [],
    max_daily_capacity: 3,
    current_day_bookings: 2,
    years_experience: 7,
    languages_spoken: ['Urdu', 'Pashto'],
    tier: 'standard',
  },

  // Plumbers (5)
  {
    id: 'P012',
    name: 'Saeed Plumbing Services',
    phone: '0311-2345678',
    skill: 'Plumber',
    specializations: ['Pipe Repair', 'Water Tank', 'Bathroom Fitting'],
    job_complexity_handled: ['basic', 'intermediate', 'complex'],
    certifications: ['Licensed Plumber'],
    city: 'Islamabad',
    areas: ['F-10', 'F-11', 'G-10'],
    lat: 33.6900,
    lng: 73.0400,
    rating: 4.5,
    total_reviews: 189,
    recent_review_date: '2026-05-13',
    recent_review_sentiment: 'positive',
    on_time_score: 86,
    cancellation_rate: 4,
    reliability_score: 83,
    risk_score: 'low',
    dispute_count: 1,
    visit_fee: 400,
    hourly_rate_pkr: 1000,
    rate_per_km: 20,
    loyalty_discount: 5,
    available: true,
    booked_slots: [],
    max_daily_capacity: 4,
    current_day_bookings: 2,
    years_experience: 9,
    languages_spoken: ['Urdu'],
    tier: 'standard',
  },
  {
    id: 'P013',
    name: 'Javed Water Solutions',
    phone: '0312-3456789',
    skill: 'Plumber',
    specializations: ['Leak Detection', 'Sewer Line'],
    job_complexity_handled: ['intermediate', 'complex'],
    certifications: [],
    city: 'Karachi',
    areas: ['PECHS', 'FB Area'],
    lat: 24.8700,
    lng: 67.0300,
    rating: 4.0,
    total_reviews: 98,
    recent_review_date: '2026-04-25',
    recent_review_sentiment: 'neutral',
    on_time_score: 70,
    cancellation_rate: 9,
    reliability_score: 68,
    risk_score: 'medium',
    dispute_count: 4,
    visit_fee: 350,
    hourly_rate_pkr: 900,
    rate_per_km: 25,
    loyalty_discount: 0,
    available: true,
    booked_slots: [],
    max_daily_capacity: 3,
    current_day_bookings: 1,
    years_experience: 6,
    languages_spoken: ['Urdu', 'Sindhi'],
    tier: 'basic',
  },
  {
    id: 'P014',
    name: 'Pervez Plumbing Pro',
    phone: '0313-4567890',
    skill: 'Plumber',
    specializations: ['Bathroom Renovation', 'Water Heater'],
    job_complexity_handled: ['basic', 'intermediate', 'complex'],
    certifications: ['Licensed Plumber'],
    city: 'Lahore',
    areas: ['Wapda Town', 'Green Town'],
    lat: 31.5100,
    lng: 74.3100,
    rating: 4.7,
    total_reviews: 345,
    recent_review_date: '2026-05-17',
    recent_review_sentiment: 'positive',
    on_time_score: 92,
    cancellation_rate: 2,
    reliability_score: 90,
    risk_score: 'low',
    dispute_count: 0,
    visit_fee: 500,
    hourly_rate_pkr: 1400,
    rate_per_km: 20,
    loyalty_discount: 5,
    available: true,
    booked_slots: [],
    max_daily_capacity: 4,
    current_day_bookings: 3,
    years_experience: 14,
    languages_spoken: ['Urdu', 'Punjabi'],
    tier: 'premium',
  },
  {
    id: 'P015',
    name: 'Zahid Pipe Works',
    phone: '0314-5678901',
    skill: 'Plumber',
    specializations: ['Pipe Fitting', 'Tap Repair'],
    job_complexity_handled: ['basic'],
    certifications: [],
    city: 'Multan',
    areas: ['Cantt', 'Shah Shams'],
    lat: 30.1900,
    lng: 71.4800,
    rating: 3.9,
    total_reviews: 67,
    recent_review_date: '2026-04-10',
    recent_review_sentiment: 'neutral',
    on_time_score: 65,
    cancellation_rate: 11,
    reliability_score: 60,
    risk_score: 'medium',
    dispute_count: 3,
    visit_fee: 250,
    hourly_rate_pkr: 700,
    rate_per_km: 15,
    loyalty_discount: 0,
    available: true,
    booked_slots: [],
    max_daily_capacity: 3,
    current_day_bookings: 1,
    years_experience: 4,
    languages_spoken: ['Urdu', 'Saraiki'],
    tier: 'basic',
  },
  {
    id: 'P016',
    name: 'Asad Plumbing Expert',
    phone: '0315-6789012',
    skill: 'Plumber',
    specializations: ['Water Pump', 'Overhead Tank'],
    job_complexity_handled: ['intermediate'],
    certifications: [],
    city: 'Peshawar',
    areas: ['Ring Road', 'Matni'],
    lat: 34.0200,
    lng: 71.5500,
    rating: 4.2,
    total_reviews: 145,
    recent_review_date: '2026-05-08',
    recent_review_sentiment: 'positive',
    on_time_score: 80,
    cancellation_rate: 6,
    reliability_score: 76,
    risk_score: 'low',
    dispute_count: 2,
    visit_fee: 350,
    hourly_rate_pkr: 950,
    rate_per_km: 20,
    loyalty_discount: 5,
    available: true,
    booked_slots: [],
    max_daily_capacity: 3,
    current_day_bookings: 2,
    years_experience: 7,
    languages_spoken: ['Urdu', 'Pashto'],
    tier: 'standard',
  },

  // Home Tutors (5)
  {
    id: 'P017',
    name: 'Dr. Ayesha Tutoring',
    phone: '0316-7890123',
    skill: 'Home Tutor',
    specializations: ['Mathematics', 'Physics', 'Chemistry'],
    job_complexity_handled: ['basic', 'intermediate', 'complex'],
    certifications: ['PhD Physics', 'Teaching Certified'],
    city: 'Islamabad',
    areas: ['F-8', 'F-7', 'G-6'],
    lat: 33.7200,
    lng: 73.0600,
    rating: 4.9,
    total_reviews: 520,
    recent_review_date: '2026-05-18',
    recent_review_sentiment: 'positive',
    on_time_score: 98,
    cancellation_rate: 1,
    reliability_score: 97,
    risk_score: 'low',
    dispute_count: 0,
    visit_fee: 800,
    hourly_rate_pkr: 2000,
    rate_per_km: 20,
    loyalty_discount: 10,
    available: true,
    booked_slots: [],
    max_daily_capacity: 6,
    current_day_bookings: 4,
    years_experience: 15,
    languages_spoken: ['Urdu', 'English'],
    tier: 'premium',
  },
  {
    id: 'P018',
    name: 'Hassan Academy',
    phone: '0317-8901234',
    skill: 'Home Tutor',
    specializations: ['English', 'Urdu', 'Islamiat'],
    job_complexity_handled: ['basic', 'intermediate'],
    certifications: ['MA English'],
    city: 'Karachi',
    areas: ['Gulshan-e-Iqbal', 'Nipa'],
    lat: 24.9000,
    lng: 67.0900,
    rating: 4.3,
    total_reviews: 210,
    recent_review_date: '2026-05-10',
    recent_review_sentiment: 'positive',
    on_time_score: 84,
    cancellation_rate: 5,
    reliability_score: 80,
    risk_score: 'low',
    dispute_count: 1,
    visit_fee: 500,
    hourly_rate_pkr: 1200,
    rate_per_km: 25,
    loyalty_discount: 5,
    available: true,
    booked_slots: [],
    max_daily_capacity: 5,
    current_day_bookings: 3,
    years_experience: 8,
    languages_spoken: ['Urdu', 'English', 'Sindhi'],
    tier: 'standard',
  },
  {
    id: 'P019',
    name: 'Sara Home Lessons',
    phone: '0318-9012345',
    skill: 'Home Tutor',
    specializations: ['Biology', 'Chemistry', 'O/A Levels'],
    job_complexity_handled: ['intermediate', 'complex'],
    certifications: ['MBBS', 'Teaching Certified'],
    city: 'Lahore',
    areas: ['Cantt', 'Malir Cantt'],
    lat: 31.5500,
    lng: 74.3800,
    rating: 4.6,
    total_reviews: 178,
    recent_review_date: '2026-05-14',
    recent_review_sentiment: 'positive',
    on_time_score: 88,
    cancellation_rate: 3,
    reliability_score: 86,
    risk_score: 'low',
    dispute_count: 1,
    visit_fee: 600,
    hourly_rate_pkr: 1500,
    rate_per_km: 20,
    loyalty_discount: 5,
    available: true,
    booked_slots: [],
    max_daily_capacity: 4,
    current_day_bookings: 2,
    years_experience: 10,
    languages_spoken: ['Urdu', 'English'],
    tier: 'premium',
  },
  {
    id: 'P020',
    name: 'Kamran Tutoring Center',
    phone: '0319-0123456',
    skill: 'Home Tutor',
    specializations: ['Mathematics', 'Statistics'],
    job_complexity_handled: ['basic', 'intermediate'],
    certifications: ['MSc Math'],
    city: 'Multan',
    areas: ['Gulgasht', 'People\'s Colony'],
    lat: 30.2100,
    lng: 71.5000,
    rating: 4.1,
    total_reviews: 95,
    recent_review_date: '2026-04-30',
    recent_review_sentiment: 'positive',
    on_time_score: 76,
    cancellation_rate: 7,
    reliability_score: 72,
    risk_score: 'medium',
    dispute_count: 2,
    visit_fee: 350,
    hourly_rate_pkr: 800,
    rate_per_km: 15,
    loyalty_discount: 0,
    available: true,
    booked_slots: [],
    max_daily_capacity: 4,
    current_day_bookings: 2,
    years_experience: 5,
    languages_spoken: ['Urdu', 'Saraiki'],
    tier: 'basic',
  },
  {
    id: 'P021',
    name: 'Fatima Educational Services',
    phone: '0320-1234567',
    skill: 'Home Tutor',
    specializations: ['Quran', 'Islamiat', 'Arabic'],
    job_complexity_handled: ['basic', 'intermediate'],
    certifications: ['Hafiz-e-Quran', 'Maulvi'],
    city: 'Peshawar',
    areas: ['Qissa Khwani', 'Andar Shehr'],
    lat: 34.0050,
    lng: 71.5750,
    rating: 4.8,
    total_reviews: 380,
    recent_review_date: '2026-05-16',
    recent_review_sentiment: 'positive',
    on_time_score: 96,
    cancellation_rate: 1,
    reliability_score: 95,
    risk_score: 'low',
    dispute_count: 0,
    visit_fee: 400,
    hourly_rate_pkr: 1000,
    rate_per_km: 20,
    loyalty_discount: 5,
    available: true,
    booked_slots: [],
    max_daily_capacity: 6,
    current_day_bookings: 4,
    years_experience: 12,
    languages_spoken: ['Urdu', 'Pashto', 'Arabic'],
    tier: 'premium',
  },

  // Mechanics (4)
  {
    id: 'P022',
    name: 'Shahid Auto Works',
    phone: '0321-2345678',
    skill: 'Mechanic',
    specializations: ['Engine Repair', 'Oil Change', 'Brake Service'],
    job_complexity_handled: ['basic', 'intermediate', 'complex'],
    certifications: ['Toyota Certified'],
    city: 'Islamabad',
    areas: ['I-8', 'I-9', 'G-13'],
    lat: 33.6600,
    lng: 73.0200,
    rating: 4.4,
    total_reviews: 234,
    recent_review_date: '2026-05-15',
    recent_review_sentiment: 'positive',
    on_time_score: 83,
    cancellation_rate: 5,
    reliability_score: 80,
    risk_score: 'low',
    dispute_count: 2,
    visit_fee: 500,
    hourly_rate_pkr: 1200,
    rate_per_km: 25,
    loyalty_discount: 5,
    available: true,
    booked_slots: [],
    max_daily_capacity: 3,
    current_day_bookings: 2,
    years_experience: 11,
    languages_spoken: ['Urdu', 'Punjabi'],
    tier: 'standard',
  },
  {
    id: 'P023',
    name: 'Rashid Mobile Mechanic',
    phone: '0322-3456789',
    skill: 'Mechanic',
    specializations: ['Battery Jump', 'Tire Change', 'Minor Repairs'],
    job_complexity_handled: ['basic', 'intermediate'],
    certifications: [],
    city: 'Karachi',
    areas: ['Korangi', 'Landhi'],
    lat: 24.8300,
    lng: 67.1200,
    rating: 4.0,
    total_reviews: 112,
    recent_review_date: '2026-05-02',
    recent_review_sentiment: 'neutral',
    on_time_score: 72,
    cancellation_rate: 8,
    reliability_score: 68,
    risk_score: 'medium',
    dispute_count: 3,
    visit_fee: 400,
    hourly_rate_pkr: 900,
    rate_per_km: 30,
    loyalty_discount: 0,
    available: true,
    booked_slots: [],
    max_daily_capacity: 4,
    current_day_bookings: 2,
    years_experience: 6,
    languages_spoken: ['Urdu', 'Sindhi'],
    tier: 'basic',
  },
  {
    id: 'P024',
    name: 'Waseem Car Care',
    phone: '0323-4567890',
    skill: 'Mechanic',
    specializations: ['AC Repair', 'Engine Tuning', 'Diagnostics'],
    job_complexity_handled: ['intermediate', 'complex'],
    certifications: ['Honda Certified', 'Diagnostic Specialist'],
    city: 'Lahore',
    areas: ['Liberty', 'Main Market'],
    lat: 31.5100,
    lng: 74.3500,
    rating: 4.7,
    total_reviews: 310,
    recent_review_date: '2026-05-17',
    recent_review_sentiment: 'positive',
    on_time_score: 91,
    cancellation_rate: 2,
    reliability_score: 89,
    risk_score: 'low',
    dispute_count: 1,
    visit_fee: 600,
    hourly_rate_pkr: 1500,
    rate_per_km: 20,
    loyalty_discount: 5,
    available: true,
    booked_slots: [],
    max_daily_capacity: 3,
    current_day_bookings: 1,
    years_experience: 13,
    languages_spoken: ['Urdu', 'Punjabi', 'English'],
    tier: 'premium',
  },
  {
    id: 'P025',
    name: 'Amir Bike & Car Service',
    phone: '0324-5678901',
    skill: 'Mechanic',
    specializations: ['Bike Repair', 'Car Service'],
    job_complexity_handled: ['basic', 'intermediate'],
    certifications: [],
    city: 'Multan',
    areas: ['Abdali Road', 'Dhok Bazar'],
    lat: 30.1800,
    lng: 71.4700,
    rating: 3.9,
    total_reviews: 78,
    recent_review_date: '2026-04-18',
    recent_review_sentiment: 'neutral',
    on_time_score: 68,
    cancellation_rate: 10,
    reliability_score: 62,
    risk_score: 'medium',
    dispute_count: 4,
    visit_fee: 300,
    hourly_rate_pkr: 700,
    rate_per_km: 15,
    loyalty_discount: 0,
    available: true,
    booked_slots: [],
    max_daily_capacity: 3,
    current_day_bookings: 1,
    years_experience: 4,
    languages_spoken: ['Urdu', 'Saraiki'],
    tier: 'basic',
  },
]

export async function GET() {
  const supabase = createAdminClient()

  // Check if providers already exist
  const { count } = await supabase
    .from('providers')
    .select('*', { count: 'exact', head: true })

  if (count && count > 0) {
    return NextResponse.json({ message: 'Providers already seeded', count })
  }

  // Insert all providers
  const { error } = await supabase.from('providers').insert(providers as any)

  if (error) {
    return NextResponse.json({ error: error.message }, { status: 500 })
  }

  return NextResponse.json({ message: 'Providers seeded successfully', count: providers.length })
}
